version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.8-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env/.env.prod.db
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: